"""Emit the report's LaTeX tables from the result JSONs.

Keeping the tables generated rather than hand-typed means the numbers in the PDF
cannot drift from ``results/*.json``. ``report/report.tex`` pulls them in with
``\\input{tables/...}``.

Usage::

    python scripts/make_report_tables.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from variants import DISPLAY_NAMES, FAMILIES, load_runs, select_best  # noqa: E402

BASELINE_LABELS = {
    "naive_last_value": "Naive last value",
    "lag24_repeat": "Seasonal naive, lag 24",
    "lag168_repeat": "Seasonal naive, lag 168",
    "seasonal_mean": "Seasonal mean, dow$\\times$hour",
}

ABLATION_LABELS = {
    "patchtst_reference": "PatchTST-cov (ref.)",
    "patchtst_no_future_tokens": "\\quad no future cov.\\ tokens",
    "patchtst_target_only": "\\quad no covariates (vanilla)",
    "patchtst_no_pointwise_head": "\\quad no pointwise path",
    "patchtst_no_series_embedding": "\\quad no series embedding",
    "patchtst_no_revin": "\\quad no RevIN",
    "patchtst_patch8": "\\quad patch 8, step 4",
    "patchtst_patch48": "\\quad patch 48, step 24",
    "patchtst_mse_loss": "\\quad MSE instead of $L_1$",
    "lstm_reference": "LSTM+Attention (ref.)",
    "lstm_no_attention": "\\quad no attention",
    "lstm_no_series_embedding": "\\quad no series embedding",
    "lstm_no_revin": "\\quad no RevIN",
    "lstm_teacher_forcing_only": "\\quad teacher forcing only",
    "lstm_free_running_only": "\\quad free running only",
    "lstm_target_only": "\\quad no covariates",
}

JENA_LABELS = {
    "naive_last_value": "Naive last value",
    "lag24_repeat": "Seasonal naive, lag 24",
    "seasonal_mean": "Seasonal mean",
    "patchtst": "PatchTST-cov (ours)",
    "lstm_attention": "LSTM+Attention (ours)",
}


#: Every macro the report references, with a visible placeholder default. Emitting
#: the full set unconditionally keeps ``report.tex`` compilable while experiments
#: are still running, and makes a missing number obvious in the PDF.
MACRO_NAMES = (
    "naiveValWape", "naiveTestWape", "seasonalValWape", "seasonalTestWape",
    "patchValWape", "patchTestWape", "patchEpochs", "patchParams", "patchMinutes",
    "lstmValWape", "lstmTestWape", "lstmEpochs", "lstmParams", "lstmMinutes",
    "ensValWape", "ensTestWape", "ensValMae", "ensWeight", "ensVsNaive", "ensVsSeasonal",
    "gapValWape", "lstmRevinValWape", "lstmRevinTestWape",
    "patchRevinValWape", "patchRevinTestWape",
)

PLACEHOLDER = "\\textbf{??}"


def load(path: Path) -> dict | None:
    if not path.exists():
        print(f"  (missing {path.name}, skipped)")
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def fmt(value: float | None, digits: int = 2) -> str:
    return "--" if value is None else f"{value:.{digits}f}"


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path)


def benchmark_table(results_dir: Path, out: Path) -> None:
    baselines = load(results_dir / "baselines_local.json")
    runs = load_runs(results_dir)
    ensemble = load(results_dir / "ensemble.json")
    if baselines is None:
        write(out, ["\\emph{Pending: run scripts/run\\_all.sh to populate this table.}"])
        return
    chosen = select_best(results_dir)

    rows: list[tuple[str, dict | None, dict | None, str]] = []
    for key, label in BASELINE_LABELS.items():
        entry = baselines.get(key, {})
        rows.append((label, entry.get("local_val"), entry.get("local_test"), ""))
    for family, candidates in FAMILIES.items():
        for tag in candidates:
            if tag not in runs:
                continue
            label = DISPLAY_NAMES[tag]
            if chosen.get(family) == tag:
                label += "$^{\\ast}$"
            rows.append((label, runs[tag].get("val"), runs[tag].get("test"), ""))
    if ensemble:
        rows.append((
            f"Blend of the two starred, $w{{=}}{ensemble['weight']:.2f}$",
            ensemble.get("val"),
            ensemble.get("test"),
            "",
        ))

    best_val = min((row[1]["wape"] for row in rows if row[1]), default=None)
    best_test = min((row[2]["wape"] for row in rows if row[2]), default=None)

    lines = [
        "% generated by scripts/make_report_tables.py",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "& \\multicolumn{2}{c}{Validation} & \\multicolumn{2}{c}{Test (gap)} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Method & MAE & WAPE & MAE & WAPE \\\\",
        "\\midrule",
    ]
    for label, val, test, params in rows:
        def cell(metrics: dict | None, name: str, best: float | None) -> str:
            if metrics is None:
                return "--"
            value = metrics[name]
            text = fmt(value)
            if name == "wape" and best is not None and abs(value - best) < 1e-9:
                return f"\\textbf{{{text}}}"
            return text

        del params  # parameter counts are quoted in the text instead
        lines.append(
            f"{label} & {cell(val, 'mae', None)} & {cell(val, 'wape', best_val)}"
            f" & {cell(test, 'mae', None)} & {cell(test, 'wape', best_test)} \\\\"
        )
        if label.startswith("Seasonal mean"):
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(out, lines)


def ablation_table(results_dir: Path, out: Path) -> None:
    data = load(results_dir / "ablations.json")
    if data is None:
        write(out, [r"\emph{Pending: run scripts/run\_ablations.py to populate this table.}"])
        return
    lines = [
        "% generated by scripts/make_report_tables.py",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "& \\multicolumn{2}{c}{Validation} & \\multicolumn{2}{c}{Test (336\\,h gap)} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Configuration & WAPE & $\\Delta$ & WAPE & $\\Delta$ \\\\",
        "\\midrule",
    ]
    for family, reference_key in (("patchtst", "patchtst_reference"), ("lstm", "lstm_reference")):
        reference = data.get(reference_key)
        if reference is None:
            continue
        keys = [k for k in ABLATION_LABELS if k.startswith(family) and k in data]
        keys.sort(key=lambda k: (k != reference_key, ABLATION_LABELS[k]))
        for key in keys:
            entry = data[key]
            label = ABLATION_LABELS[key]
            val, test = entry["val"]["wape"], entry["test"]["wape"]
            if key == reference_key:
                lines.append(f"{label} & {fmt(val)} & & {fmt(test)} & \\\\")
            else:
                dv = val - reference["val"]["wape"]
                dt = test - reference["test"]["wape"]
                lines.append(
                    f"{label} & {fmt(val)} & {dv:+.2f} & {fmt(test)} & {dt:+.2f} \\\\"
                )
        if family == "patchtst":
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(out, lines)


def jena_table(results_dir: Path, out: Path) -> None:
    data = load(results_dir / "jena.json")
    if data is None:
        write(out, [r"\emph{Pending: run scripts/jena\_experiment.py to populate this table.}"])
        return
    # MAE only: eight numeric columns do not fit one column, and RMSE tells the
    # same story here. The full six-metric numbers stay in results/jena.json.
    targets = sorted(data, reverse=True)  # temperature first: it is the primary target
    lines = [
        "% generated by scripts/make_report_tables.py",
        "\\begin{tabular}{l" + "rr" * len(targets) + "}",
        "\\toprule",
    ]
    group = []
    for target in targets:
        unit = "$^{\\circ}$C" if "temp" in target else "mbar"
        group.append(f"\\multicolumn{{2}}{{c}}{{{target.replace('_', ' ')} [{unit}]}}")
    lines.append("& " + " & ".join(group) + " \\\\")
    lines.append("".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(targets))))
    lines.append("Method (MAE) & " + " & ".join(["val & test"] * len(targets)) + " \\\\")
    lines.append("\\midrule")

    for key, label in JENA_LABELS.items():
        cells: list[str] = []
        present = False
        for target in targets:
            entry = data[target]
            for split in ("val", "test"):
                if key in entry.get("baselines", {}).get(split, {}):
                    metrics = entry["baselines"][split][key]
                elif key in entry and entry[key].get(split):
                    metrics = entry[key][split]
                else:
                    metrics = None
                present = present or bool(metrics)
                cells.append(fmt(metrics["mae"] if metrics else None))
        if present:
            lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
        if key == "seasonal_mean":
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(out, lines)


def macros(results_dir: Path, out: Path) -> None:
    """Numbers quoted in the prose, as LaTeX macros."""
    baselines = load(results_dir / "baselines_local.json")
    patchtst = load(results_dir / "patchtst_main.json")
    lstm = load(results_dir / "lstm_main.json")
    ensemble = load(results_dir / "ensemble.json")
    values: dict[str, str] = {name: PLACEHOLDER for name in MACRO_NAMES}
    lines = ["% generated by scripts/make_report_tables.py"]

    def macro(name: str, value: str) -> None:
        values[name] = value

    if baselines:
        macro("naiveValWape", fmt(baselines["naive_last_value"]["local_val"]["wape"]))
        macro("naiveTestWape", fmt(baselines["naive_last_value"]["local_test"]["wape"]))
        macro("seasonalValWape", fmt(baselines["seasonal_mean"]["local_val"]["wape"]))
        macro("seasonalTestWape", fmt(baselines["seasonal_mean"]["local_test"]["wape"]))
    chosen = select_best(results_dir)
    runs = load_runs(results_dir)
    if "patchtst" in chosen:
        run = runs[chosen["patchtst"]]
        macro("patchValWape", fmt(run["val"]["wape"]))
        macro("patchTestWape", fmt(run["test"]["wape"]))
        macro("patchEpochs", str(run["best_epoch"]))
        macro("patchParams", f"{run['params'] / 1e3:.0f}")
        macro("patchMinutes", f"{run['runtime_seconds'] / 60:.0f}")
    if "lstm_attention" in chosen:
        run = runs[chosen["lstm_attention"]]
        macro("lstmValWape", fmt(run["val"]["wape"]))
        macro("lstmTestWape", fmt(run["test"]["wape"]))
        macro("lstmEpochs", str(run["best_epoch"]))
        macro("lstmParams", f"{run['params'] / 1e3:.0f}")
        macro("lstmMinutes", f"{run['runtime_seconds'] / 60:.0f}")
    if "lstm_main" in runs:
        macro("lstmRevinValWape", fmt(runs["lstm_main"]["val"]["wape"]))
        macro("lstmRevinTestWape", fmt(runs["lstm_main"]["test"]["wape"]))
    if "patchtst_main" in runs:
        macro("patchRevinValWape", fmt(runs["patchtst_main"]["val"]["wape"]))
        macro("patchRevinTestWape", fmt(runs["patchtst_main"]["test"]["wape"]))
    if ensemble:
        macro("ensValWape", fmt(ensemble["val"]["wape"]))
        macro("ensTestWape", fmt(ensemble["test"]["wape"]))
        macro("ensValMae", fmt(ensemble["val"]["mae"]))
        macro("ensWeight", f"{ensemble['weight']:.2f}")
        macro("gapValWape", fmt(ensemble["val_gap"]["wape"]))
    if baselines and ensemble:
        reduction = (
            1 - ensemble["test"]["wape"] / baselines["naive_last_value"]["local_test"]["wape"]
        ) * 100
        macro("ensVsNaive", f"{reduction:.0f}")
        reduction_val = (
            1 - ensemble["val"]["wape"] / baselines["seasonal_mean"]["local_val"]["wape"]
        ) * 100
        macro("ensVsSeasonal", f"{reduction_val:.0f}")

    unresolved = [name for name, value in values.items() if value == PLACEHOLDER]
    if unresolved:
        print(f"  (unresolved macros: {', '.join(unresolved)})")
    lines += [f"\\newcommand{{\\{name}}}{{{values[name]}}}" for name in MACRO_NAMES]
    write(out, lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the report's LaTeX tables.")
    parser.add_argument("--results-dir", type=Path, default=ROOT / "results")
    parser.add_argument("--out-dir", type=Path, default=ROOT / "report" / "tables")
    args = parser.parse_args()

    benchmark_table(args.results_dir, args.out_dir / "benchmark.tex")
    ablation_table(args.results_dir, args.out_dir / "ablations.tex")
    jena_table(args.results_dir, args.out_dir / "jena.tex")
    macros(args.results_dir, args.out_dir / "macros.tex")


if __name__ == "__main__":
    main()
